{
  "requestId": null,
  "success": true,
  "resubmitToken": null,
  "msg": null,
  "content": {
    "pageNo": 2,
    "pageSize": 15,
    "positionResult": {
      "totalCount": 20,
      "locationInfo": {
        "city": "杭州",
        "district": null,
        "queryByGisCode": false,
        "businessZone": null,
        "locationCode": null
      },
      "queryAnalysisInfo": {
        "positionName": "云计算",
        "companyName": null,
        "usefulCompany": false,
        "industryName": null
      },
      "strategyProperty": {
        "name": "dm-csearch-default",
        "id": 1
      },
      "resultSize": 5,
      "result": [
        {
          "companyId": 2070,
          "positionId": 2004427,
          "industryField": "移动互联网,游戏",
          "education": "本科",
          "workYear": "3-5年",
          "city": "杭州",
          "positionAdvantage": "工作氛围好",
          "createTime": "2016-08-01 12:10:23",
          "salary": "12k-24k",
          "positionName": "资深云计算开发-Docker容器",
          "companySize": "2000人以上",
          "companyShortName": "网易",
          "formatCreateTime": "2016-08-01",
          "companyLogo": "image1/M00/28/BC/Cgo8PFVincKASgTOAABOpCn36ZQ820.jpg",
          "financeStage": "上市公司",
          "jobNature": "全职",
          "approve": 1,
          "companyLabelList": [
            "技能培训",
            "年底双薪",
            "节日礼物",
            "四星级大厨"
          ],
          "district": "滨江区",
          "score": 0,
          "businessZones": [
            "长河",
            "江南"
          ],
          "imState": "disabled",
          "lastLogin": 1470397427000,
          "publisherId": 5325551,
          "explain": null,
          "plus": null,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription": null,
          "companyFullName": "网易（杭州）网络有限公司",
          "adWord": 0
        },
        {
          "companyId": 2070,
          "positionId": 1985183,
          "industryField": "移动互联网,游戏",
          "education": "本科",
          "workYear": "3-5年",
          "city": "杭州",
          "positionAdvantage": "工作氛围好",
          "createTime": "2016-08-01 12:10:22",
          "salary": "15k-30k",
          "positionName": "战略规划专家（云计算）",
          "companySize": "2000人以上",
          "companyShortName": "网易",
          "formatCreateTime": "2016-08-01",
          "companyLogo": "image1/M00/28/BC/Cgo8PFVincKASgTOAABOpCn36ZQ820.jpg",
          "financeStage": "上市公司",
          "jobNature": "全职",
          "approve": 1,
          "companyLabelList": [
            "技能培训",
            "年底双薪",
            "节日礼物",
            "四星级大厨"
          ],
          "district": null,
          "score": 0,
          "businessZones": null,
          "imState": "disabled",
          "lastLogin": 1470397427000,
          "publisherId": 5325551,
          "explain": null,
          "plus": null,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription": null,
          "companyFullName": "网易（杭州）网络有限公司",
          "adWord": 0
        },
        {
          "companyId": 47878,
          "positionId": 2049256,
          "industryField": "移动互联网,数据服务",
          "education": "本科",
          "workYear": "3-5年",
          "city": "杭州",
          "positionAdvantage": "业务快速发展，岗位需求缺口较大晋升机会多",
          "createTime": "2016-07-04 20:26:34",
          "salary": "15k-30k",
          "positionName": "云计算工程师",
          "companySize": "2000人以上",
          "companyShortName": "华为杭州研究所",
          "formatCreateTime": "2016-07-04",
          "companyLogo": "image1/M00/00/7C/Cgo8PFTUXcCAJjziAACvkniG9bA013.jpg",
          "financeStage": "成熟型(不需要融资)",
          "jobNature": "全职",
          "approve": 0,
          "companyLabelList": [
            "技能培训",
            "股票期权",
            "岗位晋升",
            "管理规范"
          ],
          "district": "滨江区",
          "score": 0,
          "businessZones": [
            "长河",
            "西兴"
          ],
          "imState": "threeDays",
          "lastLogin": 1470395682000,
          "publisherId": 5518477,
          "explain": null,
          "plus": null,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription": null,
          "companyFullName": "杭州华为企业通信技术有限公司",
          "adWord": 0
        },
        {
          "companyId": 47878,
          "positionId": 2036680,
          "industryField": "移动互联网,数据服务",
          "education": "本科",
          "workYear": "不限",
          "city": "杭州",
          "positionAdvantage": "5险一金 各种福利保障 股票长期激励",
          "createTime": "2016-06-30 20:06:40",
          "salary": "15k-30k",
          "positionName": "云计算研发工程师",
          "companySize": "2000人以上",
          "companyShortName": "华为杭州研究所",
          "formatCreateTime": "2016-06-30",
          "companyLogo": "image1/M00/00/7C/Cgo8PFTUXcCAJjziAACvkniG9bA013.jpg",
          "financeStage": "成熟型(不需要融资)",
          "jobNature": "全职",
          "approve": 0,
          "companyLabelList": [
            "技能培训",
            "股票期权",
            "岗位晋升",
            "管理规范"
          ],
          "district": "滨江区",
          "score": 0,
          "businessZones": [
            "长河",
            "西兴"
          ],
          "imState": "today",
          "lastLogin": 1470478707000,
          "publisherId": 5514662,
          "explain": null,
          "plus": null,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription": null,
          "companyFullName": "杭州华为企业通信技术有限公司",
          "adWord": 0
        },
        {
          "companyId": 47878,
          "positionId": 1937545,
          "industryField": "移动互联网,数据服务",
          "education": "本科",
          "workYear": "5-10年",
          "city": "杭州",
          "positionAdvantage": "安全架构师,云计算,网络架构师",
          "createTime": "2016-06-08 14:17:46",
          "salary": "15k-30k",
          "positionName": "云计算架构师",
          "companySize": "2000人以上",
          "companyShortName": "华为杭州研究所",
          "formatCreateTime": "2016-06-08",
          "companyLogo": "image1/M00/00/7C/Cgo8PFTUXcCAJjziAACvkniG9bA013.jpg",
          "financeStage": "成熟型(不需要融资)",
          "jobNature": "全职",
          "approve": 0,
          "companyLabelList": [
            "技能培训",
            "股票期权",
            "岗位晋升",
            "管理规范"
          ],
          "district": "滨江区",
          "score": 0,
          "businessZones": [
            "江南",
            "近江"
          ],
          "imState": "threeDays",
          "lastLogin": 1470406320000,
          "publisherId": 5248399,
          "explain": null,
          "plus": null,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription": null,
          "companyFullName": "杭州华为企业通信技术有限公司",
          "adWord": 0
        }
      ]
    }
  },
  "code": 0
}
